version: '2'

services:
  api-gateway:
    container_name: api_gateway
    restart: always
    build: 
      context: api_gateway/
    ports: 
      - "80:81"
    networks: 
      - api_gateway

  test-application:
    container_name: test_application
    restart: always
    build: 
      context: app/
    ports: 
      - "8081:8081"
    networks: 
      - api_gateway

networks: 
  api_gateway:
    driver: bridge